// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Attr struct {
	_tab flatbuffers.Table
}

func GetRootAsAttr(buf []byte, offset flatbuffers.UOffsetT) *Attr {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Attr{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Attr) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Attr) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Attr) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Attr) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AttrStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AttrAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func AttrAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func AttrEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
