// Code generated by protoc-gen-go. DO NOT EDIT.
// source: riemann.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Time                 int64        `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	State                string       `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Service              string       `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Host                 string       `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Description          string       `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Tags                 []string     `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Ttl                  float32      `protobuf:"fixed32,8,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Attributes           []*Attribute `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty"`
	TimeMicros           int64        `protobuf:"varint,10,opt,name=time_micros,json=timeMicros,proto3" json:"time_micros,omitempty"`
	MetricSint64         int64        `protobuf:"zigzag64,13,opt,name=metric_sint64,json=metricSint64,proto3" json:"metric_sint64,omitempty"`
	MetricD              float64      `protobuf:"fixed64,14,opt,name=metric_d,json=metricD,proto3" json:"metric_d,omitempty"`
	MetricF              float32      `protobuf:"fixed32,15,opt,name=metric_f,json=metricF,proto3" json:"metric_f,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e43e81d710c3d26, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Event) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Event) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Event) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Event) GetTtl() float32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *Event) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Event) GetTimeMicros() int64 {
	if m != nil {
		return m.TimeMicros
	}
	return 0
}

func (m *Event) GetMetricSint64() int64 {
	if m != nil {
		return m.MetricSint64
	}
	return 0
}

func (m *Event) GetMetricD() float64 {
	if m != nil {
		return m.MetricD
	}
	return 0
}

func (m *Event) GetMetricF() float32 {
	if m != nil {
		return m.MetricF
	}
	return 0
}

type Query struct {
	String_              string   `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e43e81d710c3d26, []int{1}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

type Msg struct {
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Query                *Query   `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Events               []*Event `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e43e81d710c3d26, []int{2}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Msg) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Msg) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Msg) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Attribute struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e43e81d710c3d26, []int{3}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Attribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "main.Event")
	proto.RegisterType((*Query)(nil), "main.Query")
	proto.RegisterType((*Msg)(nil), "main.Msg")
	proto.RegisterType((*Attribute)(nil), "main.Attribute")
}

func init() { proto.RegisterFile("riemann.proto", fileDescriptor_0e43e81d710c3d26) }

var fileDescriptor_0e43e81d710c3d26 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x52, 0xcd, 0x6e, 0xe2, 0x30,
	0x10, 0x56, 0x12, 0x12, 0xc8, 0x64, 0x81, 0xd5, 0x68, 0xb5, 0x72, 0x4f, 0xb8, 0xe1, 0x92, 0x13,
	0x95, 0xa0, 0xea, 0xbd, 0x52, 0xdb, 0x1b, 0x87, 0xba, 0x0f, 0x80, 0x42, 0x70, 0xa9, 0x05, 0x89,
	0xa9, 0x6d, 0x90, 0x78, 0xcf, 0x3e, 0x50, 0xe5, 0x49, 0x40, 0xdc, 0xbe, 0x9f, 0x89, 0x67, 0xe6,
	0x9b, 0xc0, 0xd0, 0x28, 0x59, 0x97, 0x4d, 0x33, 0x3b, 0x18, 0xed, 0x34, 0xf6, 0xea, 0x52, 0x35,
	0xf9, 0x4f, 0x08, 0xf1, 0xeb, 0x49, 0x36, 0x0e, 0x11, 0x7a, 0x4e, 0xd5, 0x92, 0x05, 0x3c, 0x28,
	0x22, 0x41, 0x18, 0xff, 0x41, 0x6c, 0x5d, 0xe9, 0x24, 0x0b, 0x79, 0x50, 0xa4, 0xa2, 0x25, 0xc8,
	0xa0, 0x6f, 0xa5, 0x39, 0xa9, 0x4a, 0xb2, 0x88, 0xf4, 0x0b, 0xf5, 0x6f, 0x7c, 0x69, 0xeb, 0x58,
	0x8f, 0x64, 0xc2, 0xc8, 0x21, 0xdb, 0x48, 0x5b, 0x19, 0x75, 0x70, 0x4a, 0x37, 0x2c, 0x26, 0xeb,
	0x56, 0xa2, 0xce, 0xe5, 0xd6, 0xb2, 0x3e, 0x8f, 0xfc, 0x57, 0x1e, 0xe3, 0x5f, 0x88, 0x9c, 0xdb,
	0xb3, 0x01, 0x0f, 0x8a, 0x50, 0x78, 0x88, 0x0f, 0x00, 0xa5, 0x73, 0x46, 0xad, 0x8f, 0x4e, 0x5a,
	0x96, 0xf2, 0xa8, 0xc8, 0xe6, 0xe3, 0x99, 0x5f, 0x62, 0xf6, 0x7c, 0xd1, 0xc5, 0x4d, 0x09, 0x4e,
	0x20, 0xf3, 0x4b, 0xac, 0x6a, 0x55, 0x19, 0x6d, 0x19, 0xd0, 0x5e, 0xe0, 0xa5, 0x25, 0x29, 0x38,
	0x85, 0x61, 0x2d, 0x9d, 0x51, 0xd5, 0xca, 0xaa, 0xc6, 0x3d, 0x3d, 0xb2, 0x21, 0x0f, 0x0a, 0x14,
	0x7f, 0x5a, 0xf1, 0x83, 0x34, 0xbc, 0x83, 0x41, 0x57, 0xb4, 0x61, 0x23, 0x1e, 0x14, 0x81, 0xe8,
	0xb7, 0xfc, 0xe5, 0xc6, 0xfa, 0x64, 0x63, 0x1a, 0xb4, 0xb3, 0xde, 0xf2, 0x09, 0xc4, 0xef, 0x47,
	0x69, 0xce, 0xf8, 0x1f, 0x12, 0xeb, 0x8c, 0x6a, 0xb6, 0x94, 0x6b, 0x2a, 0x3a, 0x96, 0x5b, 0x88,
	0x96, 0x76, 0x8b, 0x23, 0x08, 0xf5, 0x8e, 0xd2, 0x1d, 0x88, 0x50, 0xef, 0x7c, 0xe0, 0xd2, 0x18,
	0x6d, 0xba, 0x60, 0x5b, 0x82, 0xf7, 0x10, 0x7f, 0xfb, 0xd7, 0x28, 0xbc, 0x6c, 0x9e, 0xb5, 0x5b,
	0x53, 0x03, 0xd1, 0x3a, 0x38, 0x85, 0x44, 0xfa, 0x33, 0x5a, 0x96, 0x50, 0x32, 0x5d, 0x0d, 0x9d,
	0x56, 0x74, 0x56, 0xbe, 0x80, 0xf4, 0x1a, 0x95, 0x4f, 0x78, 0x27, 0xcf, 0xdd, 0x58, 0x1e, 0xfa,
	0xe6, 0xa7, 0x72, 0x7f, 0xbc, 0x5e, 0x9b, 0xc8, 0x3a, 0xa1, 0xdf, 0x65, 0xf1, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x64, 0x6c, 0xcc, 0x9a, 0x3f, 0x02, 0x00, 0x00,
}
